version: '3'

dotenv: ['.env']

tasks:
  yamount:
    cmds:
    - rclone mount yandex:/ /home/georgiy/Yandex-disk
  yasync:
    deps: [documents_sync, pictures_sync]
  notes_sync:
    dir: '/home/georgiy/Documents/Notes/My_vault/'
    cmds:
    - echo "BACKING UP NOTES"
    - echo ""
    - echo $PWD
    - git add .
    - git commit -m "new notes"
    - git pull
    - git push
  documents_sync:
    cmds:
    - echo "SYNCING DOCUMENTS"
    - echo ""
    - rclone copy -P -u /home/georgiy/Documents yandex:/Documents
  pictures_sync:
    cmds:
    - echo "SYNCING PICTURES"
    - echo ""
    - rclone copy -P -u /home/georgiy/Pictures yandex:/Pictures
  jjpush:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
    - jj b set {{.CLI_ARGS}} -r @
    - jj git push -b {{.CLI_ARGS}}
    - jj new
