return {
  -- 'windwp/nvim-autopairs',
  -- event = { 'InsertEnter' },
  -- dependencies = {
  --   'hrsh7th/nvim-cmp',
  -- },
  -- config = function()
  --   local autopairs = require 'nvim-autopairs'
  --   local Rule = require 'nvim-autopairs.rule'
  --   local cmp_autopairs = require 'nvim-autopairs.completion.cmp'
  --   local cmp = require 'cmp'
  --
  --   -- configure autopairs
  --   autopairs.setup {
  --     check_ts = true,
  --     ts_config = {
  --       lua = { 'string' }, -- it will not add a pair on that treesitter node
  --       javascript = { 'template_string' },
  --       java = false,
  --     },
  --     enable_check_bracket_line = false,
  --     ignored_next_char = '[%w%.]',
  --     map_cr = true,
  --     fast_wrap = {
  --       map = '<M-e>',
  --       chars = { '{', '[', '(', '"', "'" },
  --       pattern = string.gsub([[ [%'%"%)%>%]%)%}%,] ]], '%s+', ''),
  --       offset = 0,
  --       end_key = '$',
  --       keys = 'qwertyuiopzxcvbnmasdfghjkl',
  --       check_comma = true,
  --       highlight = 'PmenuSel',
  --       highlight_grey = 'LineNr',
  --     },
  --   }
  --
  --   cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done)
  --
  --   local ts_conds = require 'nvim-autopairs.ts-conds'
  --
  --   -- press % => %% only while inside a comment or string
  --   autopairs.add_rules {
  --     Rule('%', '%', 'lua'):with_pair(ts_conds.is_ts_node { 'string', 'comment' }),
  --     Rule('$', '$', 'lua'):with_pair(ts_conds.is_not_ts_node { 'function' }),
  --   }
  -- end,
}
