return {
  -- 'numToStr/Navigator.nvim',
  -- config = function()
  --   require('Navigator').setup()
  --   local navigator = require 'Navigator'
  --   vim.keymap.set({ 'n', 't' }, '<M-h>', function()
  --     navigator.left()
  --   end)
  --   vim.keymap.set({ 'n', 't' }, '<M-l>', function()
  --     navigator.right()
  --   end)
  --   vim.keymap.set({ 'n', 't' }, '<M-k>', function()
  --     navigator.up()
  --   end)
  --   vim.keymap.set({ 'n', 't' }, '<M-j>', function()
  --     navigator.down()
  --   end)
  --   vim.keymap.set({ 'n', 't' }, '<M-[>', function()
  --     navigator.previous()
  --   end)
  -- end,
}
