return {
  -- 'hiphish/rainbow-delimiters.nvim',
  -- name = 'rainbow_delimiters',
  -- event = { 'BufReadPre', 'BufNewFile' },
  -- config = function()
  --   local rainbow_delimiters = require 'rainbow-delimiters'
  --
  --   vim.g.rainbow_delimiters = {
  --     strategy = {
  --       [''] = rainbow_delimiters.strategy['global'],
  --       vim = rainbow_delimiters.strategy['local'],
  --     },
  --     query = {
  --       [''] = 'rainbow-delimiters',
  --       lua = 'rainbow-blocks',
  --     },
  --     highlight = {
  --       'RainbowDelimiterRed',
  --       'RainbowDelimiterOrange',
  --       'RainbowDelimiterYellow',
  --       'RainbowDelimiterGreen',
  --       'RainbowDelimiterBlue',
  --       'RainbowDelimiterViolet',
  --       'RainbowDelimiterCyan',
  --     },
  --   }
  -- end,
}
