require 'custom.config.functions'
require 'custom.config.options'
require 'custom.config.russian'
require 'custom.config.keymaps'
require 'custom.config.diagnostics'
require 'custom.config.lsp'
require 'custom.config.lazy'
